### ISSUE TITLE
容器化部署貌似无视CRON_EXPRESSION导致频繁调用接口被封进而401错误

### ISSUE THREAD

**Issue by fishfree** [cooderl/wewe-rss#149]
我即使显示地在docker-compose.yml加上：
```
    environment:
      ******
      CRON_EXPRESSION: "30 4 * * *"
      MYSQL_DATABASE: 'wewe-rss'
```
每天都发现无法更新，今天看了下：`docker-compose logs -f`
结果，发现是每分钟都在拉取，这不封才怪！
![image](https://github.com/cooderl/wewe-rss/assets/1741341/c6b0f9d8-75db-4cad-9ef0-d2f6c47856c9)

最新的docker-compose的，v2.3.1

如果无法重新打包容器，可否先告知一个临时调整方法？我登入到容器内执行`crontab -e`也看不到任何计划任务项。
