### ISSUE TITLE
yaml部署失败

### ISSUE THREAD

**Issue by zymshirley** [cooderl/wewe-rss#239]
我看日志好像是数据库的问题，但具体什么问题看不出来
<img width="1016" alt="螢幕截圖 2024-09-01 下午1 05 48" src="https://github.com/user-attachments/assets/0c7439dd-7676-416e-926a-fd2abea3587d">
<img width="1481" alt="螢幕截圖 2024-09-01 下午1 06 35" src="https://github.com/user-attachments/assets/078caa5e-ee68-412d-bf7f-486e4d4a4531">

**Comment by zymshirley** [comment]
yaml部署我是按照文档给的，除了外网地址改成自己的，其他全都没有改

**Comment by wyn-ying** [comment]
群晖上直接跑docker-compose可以启动，没有复现这个问题。
日志信息看起来是wewe-rss无法访问到mysql容器，可以确认一下：wewe-rss容器的DATABASE_URL参数，是否和mysql容器的信息匹配；以及是否使用了Docker network，network和DATABASE_URL参数中的地址是否匹配

**Comment by huluohu** [comment]
![image](https://github.com/user-attachments/assets/a55cc3c2-7218-48ad-9217-b7f134becb6d)
1、cron表达式没设置
2、连不上mysql
game over！

**Comment by huluohu** [comment]
```yml
version: '3.9'
services:
  wewe-rss:
    image: cooderl/wewe-rss-sqlite:latest
    container_name: wewe-rss
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 4000:4000
    environment:
      - DATABASE_TYPE=sqlite
      # 服务接口请求授权码
      - AUTH_CODE=123456
      # 提取全文内容模式
      - FEED_MODE=fulltext
      # 定时更新订阅源Cron表达式
      - CRON_EXPRESSION=35 5,17 * * *
      # 服务接口请求限制，每分钟请求次数
      - MAX_REQUEST_PER_MINUTE=60
      # 外网访问时，需设置为服务器的公网 IP 或者域名地址
      - SERVER_ORIGIN_URL=https://werss.yourdomain.com

    volumes:
      # 映射数据库文件存储位置，容器重启后不丢失
      - /share/Container/wewerss/data:/app/data
    logging:
      options:
          max-size: "5m"
          max-file: "5"
```

这是我的，用的是sqlite，你参考。
