### ISSUE TITLE
我重装系统后，出现报错'Cannot find module '/app/docker-bootstrap.sh''

### ISSUE THREAD

**Issue by katfionn** [cooderl/wewe-rss#253]
## 报错
Error: Cannot find module '/app/docker-bootstrap.sh'

## 环境
系统：debian11 amd64
面板：casaos V0.4.11
wewe-rss版本：v2.3.1

## 已尝试并确认
1. 数据库存在并可以连接
2. 端口没有被占用
3. docker运行正常

## casaos的一键导出的yaml配置
```
name: focused_federico
services:
  app:
    cpu_shares: 90
    command: []
    container_name: wewe-rss
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - AUTH_CODE=123567
      - CRON_EXPRESSION=5 0,6,12,18 * * *
      - DATABASE_URL=mysql://root:{{mypawd}}@{{mysql}}/wewe-rss?schema
      - FEED_MODE=fulltext
      - MAX_REQUEST_PER_MINUTE=60
      - SERVER_ORIGIN_URL=http://mydomain:4000
      - TZ=Asia/Shanghai
    hostname: wewe-rss
    image: cooderl/wewe-rss:v2.3.1
    labels:
      icon: https://raw.githubusercontent.com/cooderl/wewe-rss/main/assets/logo.png
    ports:
      - target: 4000
        published: "4000"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/wewe-rss/app/app
        target: /app
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://raw.githubusercontent.com/cooderl/wewe-rss/main/assets/logo.png
  index: /
  is_uncontrolled: false
  port_map: "4000"
  scheme: http
  store_app_id: focused_federico
  title:
    custom: 公众号订阅器
```
