### ISSUE TITLE
请求失败!

### ISSUE THREAD

**Issue by yaotutu** [cooderl/wewe-rss#3]
compose 文件如下，基本上复制了readme的配置文件,只是去掉了BASE_PATH变量，项目跑起来以后进去web端，一直报错。
```
version: "3.9"

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: "Asia/Shanghai"
      MYSQL_DATABASE: "wewe-rss"
    # ports:
    #   - 13306:3306
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 45s
      interval: 10s
      retries: 10

  server:
    image: cooderl/wewe-rss-server:latest
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://root:123456@db:3306/wewe-rss?schema=public&connect_timeout=30&pool_timeout=30&socket_timeout=30
      - AUTH_CODE=123567
      - FEED_MODE=fulltext
      - MAX_REQUEST_PER_MINUTE=60
      - SERVER_ORIGIN_URL=http://localhost:4000

  web:
    image: cooderl/wewe-rss-web:latest
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_SERVER_ORIGIN_URL=http://localhost:4000

networks:
  wewe-rss:

volumes:
  db_data:

```

<img width="999" alt="image" src="https://github.com/cooderl/wewe-rss/assets/21394924/2d6f7b6f-d3fd-4cb4-8f7f-63bf363cef81">
