### ISSUE TITLE
Docker 部署创建失败

### ISSUE THREAD

**Issue by bosconb** [cooderl/wewe-rss#34]
在威联通Container Station里，按[示例](https://github.com/cooderl/wewe-rss/blob/main/docker-compose.yml)稍作修改添加后，无法下一步创建，提示我：「**请确保先配置所有必需的设置**」。请问大佬，我这种情况问题出在哪儿？

```
version: '3.9'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # 请修改为自己的密码
      MYSQL_ROOT_PASSWORD: 123456
      TZ: 'Asia/Shanghai'
      MYSQL_DATABASE: 'wewe-rss'
    ports:
      - 13306:3306
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 45s
      interval: 10s
      retries: 10

  app:
    image: cooderl/wewe-rss:latest
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy
    environment:
    # 数据库连接地址
      - DATABASE_URL=mysql://root:123456@db:3306/wewe-rss?schema=public&connect_timeout=30&pool_timeout=30&socket_timeout=30
    # 服务接口请求授权码
      - AUTH_CODE=123567
    # 提取全文内容模式
      - FEED_MODE=fulltext
    # 定时更新订阅源Cron表达式
      - CRON_EXPRESSION=35 5,17 * * *
    # 服务接口请求限制，每分钟请求次数
      - MAX_REQUEST_PER_MINUTE=60
    # 外网访问时，需设置为服务器的公网 IP 或者域名地址
      - SERVER_ORIGIN_URL=http://localhost:4000

networks:
  wewe-rss:

volumes:
  db_data:
```
