### ISSUE TITLE
添加账号扫码后显示成功后报错

### ISSUE THREAD

**Issue by ZJahon** [cooderl/wewe-rss#409]
Invalid `prisma.feed.findMany()` invocation: The table `feeds` does not exist in the current database.

**Comment by ZJahon** [comment]
重启容器后成功添加

**Comment by goasleep** [comment]
@ZJahon 你是使用mysql的容器的吧？应该是没有初始化表。 增加一个初始化的操作就好了
这是一个参考的docker-compose.yml
``` 
services:
  db:
    image: mysql:8.3.0
    container_name: wewe-rss-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: wewe-rss
      TZ: 'Asia/Shanghai'
    ports:
      - '3306:3306'
    volumes:
      - wewe_rss_db_data:/var/lib/mysql
    networks:
      - wewe-rss-network
    restart: always


  init:
    image: cooderl/wewe-rss:latest
    depends_on:
      - db
    environment:
      DATABASE_URL: 'mysql://root:123456@db:3306/wewe-rss?schema=public&connect_timeout=30&pool_timeout=30&socket_timeout=30'
    command: ["sh", "-c", "npx prisma db push"]
    restart: "no"

  wewe-rss:
    image: cooderl/wewe-rss:latest
    container_name: wewe-rss
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: 'mysql://root:123456@db:3306/wewe-rss?schema=public&connect_timeout=30&pool_timeout=30&socket_timeout=30'
      AUTH_CODE: '123567'
      FEED_MODE: 'fulltext'
      ENABLE_CLEAN_HTML: 'false'
    depends_on:
      - db
    networks:
      - wewe-rss-network
    restart: always

networks:
  wewe-rss-network:
    driver: bridge

volumes:
  wewe_rss_db_data:

```
