### ISSUE TITLE
添加账号时返回code 500

### ISSUE THREAD

**Issue by Nikkiiw** [cooderl/wewe-rss#78]
感谢您的工作！
![image](https://github.com/cooderl/wewe-rss/assets/91337184/6e8264bf-2329-48c5-8124-05ea8dd68867)

添加账号时返回code 500
已尝试docker-compose部署和docker直接部署

配置检查过应该没问题

谢谢！

附yml文件以及docker命令

```
version: '3.9'

services:
  app:
    image: cooderl/wewe-rss-sqlite:latest
    ports:
      - 4000:4000
    environment:
      # 数据库连接地址
      - DATABASE_URL=file:../data/wewe-rss.db
      - DATABASE_TYPE=sqlite
      # 服务接口请求授权码
      - AUTH_CODE=123567
      # 提取全文内容模式
      - FEED_MODE=fulltext
      # 定时更新订阅源Cron表达式
      - CRON_EXPRESSION=0 7-23/2 * * *
      # 服务接口请求限制，每分钟请求次数
      - MAX_REQUEST_PER_MINUTE=60
      # 外网访问时，需设置为服务器的公网 IP 或者域名地址
      - SERVER_ORIGIN_URL=http://XXX.XXX.XXX.XXX:4000

    volumes:
      # 映射数据库文件存储位置，容器重启后不丢失
      - ./data:/app/data

```

docker命令部署：
```
docker run -d \
  --name wewe-rss \
  -p 4000:4000 \
  -e DATABASE_TYPE=sqlite \
  -e AUTH_CODE=123567 \
  -e SERVER_ORIGIN_URL=http://xxx.xxx.xxx.xxx:4000 \
  -e MAX_REQUEST_PER_MINUTE=60 \
  -e "CRON_EXPRESSION=0 7-23/2 * * *" \
  -v /root/wewe-rss/data:/app/data \
  cooderl/wewe-rss-sqlite:latest
```
